### ISSUE TITLE
Nom d'usuari i link

### ISSUE THREAD

**Issue by agisbertb** [Desenv-Aplicacions-Multiplataforma/2DAM_2023_24_public#1]
Nom d'usuari: agisbertb
Link: https://github.com/agisbertb

**Comment by EricOrtegaGi** [comment]
Nom d'usuari: EricOrtegaGi
Link: https://github.com/EricOrtegaGi

**Comment by acacha** [comment]
Afegits https://github.com/orgs/Desenv-Aplicacions-Multiplataforma/teams/2dam_2023_24/members
